version: '3'
services:
  mysql_master_one:
    image: mysql:5.7
    container_name: "mysql_master_one"
    volumes:
      - ./master_one/conf/my.cnf:/etc/mysql/my.cnf
      - ./master_one/data:/var/lib/mysql
    restart: always
    ports:
      - 4000:3306
    env_file:
      - ./master_one/mysql_master.env

  mysql_master_two:
    image: mysql:5.7
    container_name: "mysql_master_two"
    volumes:
      - ./master_two/conf/my.cnf:/etc/mysql/my.cnf
      - ./master_two/data:/var/lib/mysql
    restart: always
    ports:
      - 4001:3306
    env_file:
      - ./master_two/mysql_master.env

  mysql_slave_two:
    image: mysql:5.7
    container_name: "mysql_slave_one"
    volumes:
      - ./slave_one/conf/my.cnf:/etc/mysql/my.cnf
      - ./slave_one/data:/var/lib/mysql
    restart: always
    ports:
      - 4002:3306
    env_file:
      - ./slave_one/mysql_slave.env

