version: "3"

services:
  mysql-5.7-single:
    container_name: mysql-5.7-single
    image: mysql:5.7
    volumes:
      - ./single:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: single
    restart: always
