version: '3'
services: 
  mysql_master_one:
    image: mysql:5.7
    container_name: "mysql_master_one"
    volumes:
      - ./master_one/conf/my.cnf:/etc/mysql/my.cnf
      - ./master_one/data:/var/lib/mysql
    restart: always
    ports: 
      - 3306:3306
    env_file: 
      - ./master_one/mysql_master.env

  mysql_slave_one:
    image: mysql:5.7
    networks: 
      - overlay
    container_name: "mysql_slave_one"
    volumes:
      - ./slave_one/conf/my.cnf:/etc/mysql/my.cnf
      - ./slave_one/data:/var/lib/mysql
    restart: always
    ports:
      - 3307:3306
    env_file:
      - ./slave_one/mysql_slave.env
    
  mysql_slave_two:
    image: mysql:5.7
    networks: 
      - overlay
    container_name: mysql_slave_two
    volumes: 
      - ./slave_two/conf/my.cnf:/etc/mysql/my.cnf
      - ./slave_two/data:/var/lib/mysql
    restart: always
    ports: 
      - 3308:3306
    env_file:
      - ./slave_two/mysql_slave.env


