version: "3"

services:
  mysql_master_1:
    image: mysql:5.7
    env_file:
      - ./master/mysql_master.env
    container_name: "mysql_master_1"
    ports:
      - 3308:3306
    volumes:
      - ./master/conf/my_1.cnf:/etc/mysql/conf.d/my.cnf
      - ./master/conf/data/master_1:/var/lib/mysql/

  mysql_master_2:
    image: mysql:5.7
    env_file:
      - ./master/mysql_master.env
    container_name: "mysql_master_2"
    ports:
      - 3309:3306
    volumes:
      - ./master/conf/my_2.cnf:/etc/mysql/conf.d/my.cnf
      - ./master/conf/data/master_2:/var/lib/mysql/

  mysql_slave_1:
    image: mysql:5.7
    env_file:
      - ./slave/mysql_slave.env
    container_name: "mysql_slave_1"
    ports:
      - 3408:3306
    volumes:
      - ./slave/conf/my_1.cnf:/etc/mysql/conf.d/my.cnf
      - ./slave/conf/data/slave_1:/var/lib/mysql/

  mysql_slave_2:
    image: mysql:5.7
    env_file:
      - ./slave/mysql_slave.env
    container_name: "mysql_slave_2"
    ports:
      - 3409:3306
    volumes:
      - ./slave/conf/my_2.cnf:/etc/mysql/conf.d/my.cnf
      - ./slave/conf/data/slave_2:/var/lib/mysql/